export const SEARCH_FOOD = "SEARCH_FOOD";
export const SET_LOADING = "SET_LOADING";
export const ADD_BTN_CLICKED = "ADD_BTN_CLICKED";
export const SHOW_FOOD_DETAILS = "SHOW_FOOD_DETAILS";
export const SET_FOOD_ITEM_CLICKED = "SET_FOOD_ITEM_CLICKED";
export const SEARCH_NUTRIENTS = "SEARCH_NUTRIENTS";
export const ADD_FOOD_ITEM = "ADD_FOOD_ITEM";
